devices:
  samplerate: 48000
  chunksize: 1024
  capture:
    type: Alsa
    device: "hw:Loopback,1,0"
    channels: 2
    format: S16LE
  playback:
    type: Alsa
    device: "__PLAYBACK_DEVICE__"
    channels: 2
    format: S16LE

pipeline:
  - type: Filter
    names:
      - peq_stack_00
      - peq_stack_01
      - peq_stack_02
      - peq_stack_03
      - peq_stack_04
      - peq_stack_05
      - peq_stack_06
      - peq_stack_07
      - peq_stack_08
      - peq_stack_09
      - peq_stack_10
      - peq_stack_11
      - peq_stack_12
      - peq_stack_13
      - peq_stack_14
      - peq_stack_15
      - peq_stack_16
      - peq_stack_17
      - peq_stack_18
      - peq_stack_19
      - peq_stack_20
      - peq_stack_21
      - peq_stack_22
      - peq_stack_23
      - peq_stack_24
      - peq_stack_25
      - peq_stack_26
      - peq_stack_27
      - peq_stack_28
      - peq_stack_29
      - peq_stack_30
      - peq_stack_31
      - peq_stack_32
      - peq_stack_33
      - peq_stack_34
      - peq_stack_35
      - peq_stack_36
      - peq_stack_37
      - peq_stack_38
      - peq_stack_39
      - peq_stack_40
      - peq_stack_41
      - peq_stack_42
      - peq_stack_43
      - peq_stack_44
      - peq_stack_45
      - peq_stack_46
      - peq_stack_47
      - peq_stack_48
      - peq_stack_49
      - peq_stack_50
      - peq_stack_51
      - peq_stack_52
      - peq_stack_53
      - peq_stack_54
      - peq_stack_55
      - peq_stack_56
      - peq_stack_57

filters:
  peq_stack_00:
    type: Biquad
    parameters:
      type: Peaking
      freq: 28.0
      gain: 0.0
      q: 1.0
  peq_stack_01:
    type: Biquad
    parameters:
      type: Peaking
      freq: 31.5
      gain: 0.0
      q: 1.0
  peq_stack_02:
    type: Biquad
    parameters:
      type: Peaking
      freq: 36.0
      gain: 0.0
      q: 1.0
  peq_stack_03:
    type: Biquad
    parameters:
      type: Peaking
      freq: 40.0
      gain: 0.0
      q: 1.0
  peq_stack_04:
    type: Biquad
    parameters:
      type: Peaking
      freq: 45.0
      gain: 0.0
      q: 1.0
  peq_stack_05:
    type: Biquad
    parameters:
      type: Peaking
      freq: 50.0
      gain: 0.0
      q: 1.0
  peq_stack_06:
    type: Biquad
    parameters:
      type: Peaking
      freq: 56.0
      gain: 0.0
      q: 1.0
  peq_stack_07:
    type: Biquad
    parameters:
      type: Peaking
      freq: 63.0
      gain: 0.0
      q: 1.0
  peq_stack_08:
    type: Biquad
    parameters:
      type: Peaking
      freq: 71.0
      gain: 0.0
      q: 1.0
  peq_stack_09:
    type: Biquad
    parameters:
      type: Peaking
      freq: 80.0
      gain: 0.0
      q: 1.0
  peq_stack_10:
    type: Biquad
    parameters:
      type: Peaking
      freq: 90.0
      gain: 0.0
      q: 1.0
  peq_stack_11:
    type: Biquad
    parameters:
      type: Peaking
      freq: 100.0
      gain: 0.0
      q: 1.0
  peq_stack_12:
    type: Biquad
    parameters:
      type: Peaking
      freq: 112.0
      gain: 0.0
      q: 1.0
  peq_stack_13:
    type: Biquad
    parameters:
      type: Peaking
      freq: 125.0
      gain: 0.0
      q: 1.0
  peq_stack_14:
    type: Biquad
    parameters:
      type: Peaking
      freq: 140.0
      gain: 0.0
      q: 1.0
  peq_stack_15:
    type: Biquad
    parameters:
      type: Peaking
      freq: 160.0
      gain: 0.0
      q: 1.0
  peq_stack_16:
    type: Biquad
    parameters:
      type: Peaking
      freq: 180.0
      gain: 0.0
      q: 1.0
  peq_stack_17:
    type: Biquad
    parameters:
      type: Peaking
      freq: 200.0
      gain: 0.0
      q: 1.0
  peq_stack_18:
    type: Biquad
    parameters:
      type: Peaking
      freq: 225.0
      gain: 0.0
      q: 1.0
  peq_stack_19:
    type: Biquad
    parameters:
      type: Peaking
      freq: 250.0
      gain: 0.0
      q: 1.0
  peq_stack_20:
    type: Biquad
    parameters:
      type: Peaking
      freq: 280.0
      gain: 0.0
      q: 1.0
  peq_stack_21:
    type: Biquad
    parameters:
      type: Peaking
      freq: 315.0
      gain: 0.0
      q: 1.0
  peq_stack_22:
    type: Biquad
    parameters:
      type: Peaking
      freq: 355.0
      gain: 0.0
      q: 1.0
  peq_stack_23:
    type: Biquad
    parameters:
      type: Peaking
      freq: 400.0
      gain: 0.0
      q: 1.0
  peq_stack_24:
    type: Biquad
    parameters:
      type: Peaking
      freq: 450.0
      gain: 0.0
      q: 1.0
  peq_stack_25:
    type: Biquad
    parameters:
      type: Peaking
      freq: 500.0
      gain: 0.0
      q: 1.0
  peq_stack_26:
    type: Biquad
    parameters:
      type: Peaking
      freq: 560.0
      gain: 0.0
      q: 1.0
  peq_stack_27:
    type: Biquad
    parameters:
      type: Peaking
      freq: 630.0
      gain: 0.0
      q: 1.0
  peq_stack_28:
    type: Biquad
    parameters:
      type: Peaking
      freq: 710.0
      gain: 0.0
      q: 1.0
  peq_stack_29:
    type: Biquad
    parameters:
      type: Peaking
      freq: 800.0
      gain: 0.0
      q: 1.0
  peq_stack_30:
    type: Biquad
    parameters:
      type: Peaking
      freq: 900.0
      gain: 0.0
      q: 1.0
  peq_stack_31:
    type: Biquad
    parameters:
      type: Peaking
      freq: 1000.0
      gain: 0.0
      q: 1.0
  peq_stack_32:
    type: Biquad
    parameters:
      type: Peaking
      freq: 1120.0
      gain: 0.0
      q: 1.0
  peq_stack_33:
    type: Biquad
    parameters:
      type: Peaking
      freq: 1250.0
      gain: 0.0
      q: 1.0
  peq_stack_34:
    type: Biquad
    parameters:
      type: Peaking
      freq: 1400.0
      gain: 0.0
      q: 1.0
  peq_stack_35:
    type: Biquad
    parameters:
      type: Peaking
      freq: 1600.0
      gain: 0.0
      q: 1.0
  peq_stack_36:
    type: Biquad
    parameters:
      type: Peaking
      freq: 1800.0
      gain: 0.0
      q: 1.0
  peq_stack_37:
    type: Biquad
    parameters:
      type: Peaking
      freq: 2000.0
      gain: 0.0
      q: 1.0
  peq_stack_38:
    type: Biquad
    parameters:
      type: Peaking
      freq: 2250.0
      gain: 0.0
      q: 1.0
  peq_stack_39:
    type: Biquad
    parameters:
      type: Peaking
      freq: 2500.0
      gain: 0.0
      q: 1.0
  peq_stack_40:
    type: Biquad
    parameters:
      type: Peaking
      freq: 2800.0
      gain: 0.0
      q: 1.0
  peq_stack_41:
    type: Biquad
    parameters:
      type: Peaking
      freq: 3150.0
      gain: 0.0
      q: 1.0
  peq_stack_42:
    type: Biquad
    parameters:
      type: Peaking
      freq: 3550.0
      gain: 0.0
      q: 1.0
  peq_stack_43:
    type: Biquad
    parameters:
      type: Peaking
      freq: 4000.0
      gain: 0.0
      q: 1.0
  peq_stack_44:
    type: Biquad
    parameters:
      type: Peaking
      freq: 4500.0
      gain: 0.0
      q: 1.0
  peq_stack_45:
    type: Biquad
    parameters:
      type: Peaking
      freq: 5000.0
      gain: 0.0
      q: 1.0
  peq_stack_46:
    type: Biquad
    parameters:
      type: Peaking
      freq: 5600.0
      gain: 0.0
      q: 1.0
  peq_stack_47:
    type: Biquad
    parameters:
      type: Peaking
      freq: 6300.0
      gain: 0.0
      q: 1.0
  peq_stack_48:
    type: Biquad
    parameters:
      type: Peaking
      freq: 7100.0
      gain: 0.0
      q: 1.0
  peq_stack_49:
    type: Biquad
    parameters:
      type: Peaking
      freq: 8000.0
      gain: 0.0
      q: 1.0
  peq_stack_50:
    type: Biquad
    parameters:
      type: Peaking
      freq: 9000.0
      gain: 0.0
      q: 1.0
  peq_stack_51:
    type: Biquad
    parameters:
      type: Peaking
      freq: 10000.0
      gain: 0.0
      q: 1.0
  peq_stack_52:
    type: Biquad
    parameters:
      type: Peaking
      freq: 11200.0
      gain: 0.0
      q: 1.0
  peq_stack_53:
    type: Biquad
    parameters:
      type: Peaking
      freq: 12500.0
      gain: 0.0
      q: 1.0
  peq_stack_54:
    type: Biquad
    parameters:
      type: Peaking
      freq: 14000.0
      gain: 0.0
      q: 1.0
  peq_stack_55:
    type: Biquad
    parameters:
      type: Peaking
      freq: 16000.0
      gain: 0.0
      q: 1.0
  peq_stack_56:
    type: Biquad
    parameters:
      type: Peaking
      freq: 18000.0
      gain: 0.0
      q: 1.0
  peq_stack_57:
    type: Biquad
    parameters:
      type: Peaking
      freq: 20000.0
      gain: 0.0
      q: 1.0

control:
  type: TcpServer
  listen: 127.0.0.1:__CAMILLA_PORT__
